# Generated by Django 5.1.15 on 2026-03-24 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngestionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset", models.CharField(max_length=50)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("records_fetched", models.IntegerField(default=0)),
                ("records_created", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Orgao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nome", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name": "Órgão",
                "verbose_name_plural": "Órgãos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Depreciacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo", models.CharField(max_length=20)),
                ("ano", models.IntegerField(db_index=True)),
                ("mes", models.IntegerField(blank=True, null=True)),
                (
                    "conta_contabil",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "custo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "orgao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depreciacoes",
                        to="costs.orgao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Depreciação",
                "verbose_name_plural": "Depreciações",
                "indexes": [models.Index(fields=["ano", "orgao"], name="costs_depre_ano_303f08_idx")],
            },
        ),
        migrations.CreateModel(
            name="DemaisCustos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo", models.CharField(max_length=20)),
                ("ano", models.IntegerField(db_index=True)),
                ("mes", models.IntegerField(blank=True, null=True)),
                (
                    "centro_custo",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "item_custo",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "custo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "orgao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demais_custos",
                        to="costs.orgao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demais Custos",
                "verbose_name_plural": "Demais Custos",
                "indexes": [models.Index(fields=["ano", "orgao"], name="costs_demai_ano_8b3c0e_idx")],
            },
        ),
        migrations.CreateModel(
            name="Pensionista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo", models.CharField(max_length=20)),
                ("ano", models.IntegerField(db_index=True)),
                ("mes", models.IntegerField(blank=True, null=True)),
                (
                    "unidade_organizacional",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "area_atuacao",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "escolaridade",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("sexo", models.CharField(blank=True, default="", max_length=20)),
                (
                    "faixa_etaria",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("forca_trabalho", models.IntegerField(default=0)),
                (
                    "custo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "orgao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pensionistas",
                        to="costs.orgao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pensionista",
                "verbose_name_plural": "Pensionistas",
                "indexes": [models.Index(fields=["ano", "orgao"], name="costs_pensi_ano_96720a_idx")],
            },
        ),
        migrations.CreateModel(
            name="PessoalAtivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo", models.CharField(max_length=20)),
                ("ano", models.IntegerField(db_index=True)),
                ("mes", models.IntegerField(blank=True, null=True)),
                (
                    "unidade_organizacional",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "area_atuacao",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "escolaridade",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("sexo", models.CharField(blank=True, default="", max_length=20)),
                (
                    "faixa_etaria",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("forca_trabalho", models.IntegerField(default=0)),
                (
                    "custo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "orgao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pessoal_ativo",
                        to="costs.orgao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pessoal Ativo",
                "verbose_name_plural": "Pessoal Ativo",
                "indexes": [models.Index(fields=["ano", "orgao"], name="costs_pesso_ano_255efb_idx")],
            },
        ),
        migrations.CreateModel(
            name="PessoalInativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo", models.CharField(max_length=20)),
                ("ano", models.IntegerField(db_index=True)),
                ("mes", models.IntegerField(blank=True, null=True)),
                (
                    "unidade_organizacional",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "area_atuacao",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "escolaridade",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("sexo", models.CharField(blank=True, default="", max_length=20)),
                (
                    "faixa_etaria",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("forca_trabalho", models.IntegerField(default=0)),
                (
                    "custo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "orgao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pessoal_inativo",
                        to="costs.orgao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pessoal Inativo",
                "verbose_name_plural": "Pessoal Inativo",
                "indexes": [models.Index(fields=["ano", "orgao"], name="costs_pesso_ano_0f27d0_idx")],
            },
        ),
        migrations.CreateModel(
            name="Transferencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo", models.CharField(max_length=20)),
                ("ano", models.IntegerField(db_index=True)),
                ("mes", models.IntegerField(blank=True, null=True)),
                (
                    "esfera_orcamentaria",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "modalidade_aplicacao",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "resultado_eof",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "custo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "orgao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transferencias",
                        to="costs.orgao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transferência",
                "verbose_name_plural": "Transferências",
                "indexes": [models.Index(fields=["ano", "orgao"], name="costs_trans_ano_f34739_idx")],
            },
        ),
    ]
